global_defs {
  enable_script_security
  script_user root
  router_id ${LB_NAME}
}

vrrp_script chk_haproxy {
  script "/etc/keepalived/check_haproxy.sh"
  interval 2
  rise 1
  fall 2
}

vrrp_instance VI_1 {
  state ${KEEPALIVED_STATE}
  interface eth0
  virtual_router_id 51
  priority ${KEEPALIVED_PRIORITY}
  advert_int 1
  unicast_src_ip ${LB_IP}
  unicast_peer {
    ${KEEPALIVED_PEER_IP}
  }
  authentication {
    auth_type PASS
    auth_pass ${KEEPALIVED_AUTH_PASS}
  }
  virtual_ipaddress {
    ${KEEPALIVED_VIP}/16 dev eth0 label eth0:vip
  }
  track_script {
    chk_haproxy
  }
}
